# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SikiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('catch_words', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('action_btn_text', models.CharField(max_length=256)),
                ('action_btn_lnk', models.URLField()),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
    ]
